# Generated by Django 5.1.4 on 2025-02-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Here you can share your email', max_length=254, null=True),
        ),
    ]
